#Objectives, notes from the textbook
#Web scraping is extracting data from a website.
#The 'rvest' web harvesting package includes functions to extract nodes of an HTML document:
#html_nodes() extracts all nodes of different types, and html_node() extracts the first node.
#html_table() converts an HTML table to a data frame.

#install.packages("rvest")

library(rvest)
url <- "https://en.wikipedia.org/wiki/Murder_in_the_United_States_by_state"
h <- read_html(url)
class(h)
#[1] "xml_document" "xml_node"

h
#outcome:{html_document} ......
# {html_document}
# <html class="client-nojs vector-feature-language-in-header-enabled vector-feature-language-in-main-page-header-disabled vector-feature-language-alert-in-sidebar-enabled vector-feature-sticky-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-enabled vector-feature-main-menu-pinned-disabled vector-feature-limited-width-enabled vector-feature-limited-width-content-enabled vector-feature-zebra-design-disabled" lang="en" dir="ltr">
# [1] <head>\n<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">\n<meta charset="UTF-8">\n<title ...
# [2] <body class="skin-vector skin-vector-search-vue mediawiki ltr sitedir-ltr mw-hide-empty-elt ns-0 ns-subject ...

tab <- h %>% html_nodes("table")
#tab
#outcome:
# {xml_nodeset (13)}
# # [1] <table class="box-Update plainlinks metadata ambox ambox-content ambox-Update" role="presentation"><tbody> ...
# # [2] <table class="wikitable">\n<caption>Legend\n</caption>\n<tbody><tr>\n<th style="background: White">Lowest\ ...
# # [3] <table class="wikitable sortable"><tbody>\n<tr>\n<th data-sort-type="text">State\n</th>\n<th data-sort-typ ...
# # [4] <table class="wikitable">\n<caption>Legend\n</caption>\n<tbody><tr>\n<th style="background: White">Lowest\ ...
# # [5] <table class="wikitable sortable"><tbody>\n<tr>\n<th data-sort-type="text">State\n</th>\n<th data-sort-typ ...
# # [6] <table class="nowraplinks mw-collapsible autocollapse navbox-inner" style="border-spacing:0;background:tra ...
#  [7] <table class="nowraplinks navbox-subgroup" style="border-spacing:0;;wide"><tbody><tr>\n<th id="Ammunition" ...
#  [8] <table class="nowraplinks navbox-subgroup" style="border-spacing:0;;wide"><tbody>\n<tr><td colspan="2" cla ...
#  [9] <table class="nowraplinks navbox-subgroup" style="border-spacing:0;;wide"><tbody><tr>\n<th id="Pistol_cali ...
# [10] <table class="nowraplinks navbox-subgroup" style="border-spacing:0;;wide"><tbody><tr>\n<th scope="row" cla ...
# [11] <table class="nowraplinks navbox-subgroup" style="border-spacing:0;;wide"><tbody>\n<tr><td colspan="2" cla ...
# [12] <table class="nowraplinks navbox-subgroup" style="border-spacing:0;;wide"><tbody>\n<tr><td colspan="2" cla ...
#[13] <table class="nowraplinks hlist mw-collapsible mw-collapsed navbox-inner" style="border-spacing:0;backgrou ...
tab1 <- tab[[3]]

tab_t <- tab1 %>% html_table
class(tab_t)
#[1] "tbl_df"     "tbl"        "data.frame"